# conda env create -n r-env --file conda.yml
# conda env update --name r-env --file conda.yml --prune 

name: r-env

channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults

dependencies:
  - conda-forge::r-base=4.3.2
  - conda-forge::r-dplyr=1.1.3
  - conda-forge::r-stringr=1.5.0
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-rcolorbrewer=1.1_3
  - conda-forge::r-cowplot=1.1.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-ggrepel=0.9.4
  - conda-forge::r-ggpubr=0.6.0
  - conda-forge::r-hmisc=5.1_1
  - conda-forge::r-survminer=0.4.9
  - conda-forge::r-survival=3.5_7
  - conda-forge::r-maxstat=0.7_25
  - bioconda::bioconductor-deseq2=1.40.2
  - bioconda::bioconductor-edger=3.42.4
  - bioconda::bioconductor-summarizedexperiment=1.30.2
  - bioconda::bioconductor-clusterprofiler=4.8.1
  - bioconda::bioconductor-tcgabiolinks=2.28.3
  - bioconda::bioconductor-biomart=2.56.1
  - bioconda::bioconductor-gsva=1.48.2
  - bioconda::bioconductor-org.hs.eg.db=3.17.0
